spring:
  rabbitmq:
    host:
    username: admin
    password: 123
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: false
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username: flashsale
    password: 123456
    hikari:
      # ????
      pool-name: DataHikariCP
      # ???????
      minimum-idle: 5
      # ?????????????600000
      idle-timeout: 180000
      # ?????
      maximum-pool-size: 10
      # ?????????????
      auto-commit: true
      # ????????
      max-lifetime: 180000
      # ??????
      connection-timeout: 30000
      # ????
      connection-test-query: SELECT 1

  data:
    redis:
      host: 175.24.181.203
      port: 6379
      database: 0
      connect-timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: 10000ms
          max-idle: 200
          min-idle: 5
  web:
    resources:
      add-mappings: true
    #启动默认静态资源处理，默认启动
    cache:
      cachecontrol:
        #缓存响应时间，单位秒
        max-age: 3600
    chain:
      #资源配链启动缓存，默认启动
      cache: true
      #启动资源链，默认禁用
      enabled: true
      #启用压缩资源（gzip，brotil）解析，默认禁用
      compressed: true
      #启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/

# mybatis plus ??
mybatis-plus:
  # ?? Mapper.xml ????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # ??Mybatis????????
  type-aliases-package: org.gotomove.flashsale.pojo

# Mybatis SQL ??????????????????mapper.xml?????
logging:
  level:
    org.gotomove.flashsale.mapper: debug